import type { Metadata } from "next";
import { AlertCircle } from "lucide-react";

export const metadata: Metadata = {
  title: "Disclaimer — Innvntory",
  description: "Operational and tax disclaimer for Innvntory by Sahaya Technologies Pvt. Ltd.",
};

export default function DisclaimerPage() {
  return (
    <div className="py-16 md:py-24">
      <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        <div className="border-b border-border-subtle pb-8 mb-10">
          <div className="inline-flex items-center gap-2 rounded-full border border-border-subtle bg-surface-muted px-3 py-0.5 text-xs font-mono text-text-secondary mb-3">
            Legal & Compliance
          </div>
          <h1 className="text-3xl sm:text-4xl font-heading font-bold text-text-primary">
            Disclaimer
          </h1>
          <p className="mt-2 text-sm text-text-muted">
            Last Updated: October 2026 • Sahaya Technologies Pvt. Ltd.
          </p>
        </div>

        <div className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-4 sm:p-5 flex items-start gap-3.5 mb-10 text-xs sm:text-sm text-text-secondary leading-relaxed">
          <AlertCircle className="h-5 w-5 text-amber-600 flex-shrink-0 mt-0.5" />
          <div>
            <span className="font-semibold text-text-primary">Provisional Document Notice: </span>
            This disclaimer clarifies the scope of accounting, tax, and inventory computation services.
          </div>
        </div>

        <div className="space-y-8 text-sm sm:text-base text-text-secondary leading-relaxed font-sans">
          <section className="space-y-3">
            <h2 className="text-xl font-heading font-bold text-text-primary">
              1. Not Formal Tax or Legal Advice
            </h2>
            <p>
              While Innvntory provides tools for GST-compliant invoicing, tax computation, and inventory valuation, output generated by the platform does not constitute professional accounting, tax, or legal advice. Businesses should independently verify filings with certified tax practitioners.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-heading font-bold text-text-primary">
              2. Accuracy of User-Supplied Master Data
            </h2>
            <p>
              Innvntory calculates inventory levels, purchase balances, and invoice totals based strictly on data entered or synchronized by authorized organization users. The platform is not liable for operational discrepancies resulting from erroneous master data or misclassified HSN codes.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
